{% set name = "pywinauto" %}
{% set version = "0.6.7" %}
{% set file_ext = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  sha256: 9da7baa9f884bf084d5362ef34863321e6d1de12731589f7a797a195306548c6

build:
  number: 0
  skip: True  # [osx or py27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - comtypes     # [win]
    - python
    - python-xlib  # [not win]
    - pywin32      # [win]
    - six

test:
  imports:
    - pywinauto
    - pywinauto.controls  # [win]
    - pywinauto.linux

about:
  home: http://pywinauto.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A set of Python modules to automate the Microsoft Windows GUI'
  doc_url: https://pywinauto.readthedocs.io/en/latest/
  dev_url: https://github.com/pywinauto/pywinauto

extra:
  recipe-maintainers:
    - m-rossi
